#pragma once

// data.h
//   auto generated by data.py

#include "os.h"

typedef struct
{
    int w;
    int h;
    const unsigned char* d;
} IconData;

typedef struct
{
    unsigned int len;
    const sint16* d;
} SampleData;

const unsigned int ZST_SIZE = 307035;
extern const unsigned char zst_block[ZST_SIZE];

const unsigned int S9X_SIZE = 71609;
extern const unsigned char s9x_block[S9X_SIZE];

extern const sint16 sample_block[];
extern const SampleData sampledata[(15*13)+8];

const int ICON_COUNT = 69;
extern const unsigned char icon_block[];
extern const IconData* icondata[ICON_COUNT];

enum {
    ICON_BG,
    ICON_BG_INFO,
    ICON_BG_MASK,
    ICON_BOMB,
    ICON_CHANGED,
    ICON_CHANNELA,
    ICON_CHANNELB,
    ICON_CHANNELC,
    ICON_CLEAR,
    ICON_DOT,
    ICON_ERASE,
    ICON_FONT,
    ICON_ICON,
    ICON_INFO,
    ICON_INST0,
    ICON_INST1,
    ICON_INST2,
    ICON_INST3,
    ICON_INST4,
    ICON_INST5,
    ICON_INST6,
    ICON_INST7,
    ICON_INST8,
    ICON_INST9,
    ICON_INSTA,
    ICON_INSTB,
    ICON_INSTC,
    ICON_INSTD,
    ICON_INSTE,
    ICON_INSTF,
    ICON_INSTX,
    ICON_LEDGER,
    ICON_LISTEN,
    ICON_LOAD,
    ICON_LOOP,
    ICON_MARIO0,
    ICON_MARIO1,
    ICON_MARIO2,
    ICON_METRE3,
    ICON_METRE4,
    ICON_MOUSE,
    ICON_NUMBER0,
    ICON_NUMBER1,
    ICON_NUMBER2,
    ICON_NUMBER3,
    ICON_NUMBER4,
    ICON_NUMBER5,
    ICON_NUMBER6,
    ICON_NUMBER7,
    ICON_NUMBER8,
    ICON_NUMBER9,
    ICON_PATTERN0,
    ICON_PATTERN1,
    ICON_PATTERN2,
    ICON_PATTERN3,
    ICON_PATTERN4,
    ICON_PATTERN5,
    ICON_PATTERN6,
    ICON_PLAY,
    ICON_QSAVE,
    ICON_SAVE,
    ICON_SCROLL,
    ICON_SCROLL_UNLIMITED,
    ICON_SEL0,
    ICON_SEL1,
    ICON_SEL2,
    ICON_STOP,
    ICON_TEMPO,
    ICON_UNDO,
};

// end of file
